### ISSUE TITLE
use zustand

### ISSUE THREAD

**Issue by saggemode** [basir/next-pg-shadcn-ecommerce#1]
1.  please can you convert the state management to zustand state
2. there is no comment section in the app
3. the final result is not the same as the intro

**Comment by basir** [comment]
hello there,
I am uploading new videos on daily basis here:
[https://www.youtube.com/watch?v=MM1qMu-sLqw&list=PLeh2GWv22bmQhKLSG7DuwptE8BGy8y3lJ&index=23&t=0s](https://www.youtube.com/watch?v=MM1qMu-sLqw&list=PLeh2GWv22bmQhKLSG7DuwptE8BGy8y3lJ&index=23)

features like review products and search products will be added soon.
we don't save any state on client side so there is no need to use packages like zustand. all cart details save on server as record in cart table.
