### ISSUE TITLE
Create product

### ISSUE THREAD

**Issue by Master2Piece** [basir/next-pg-shadcn-ecommerce#2]
Hello, im try to follow your create update product video, but 
why doesn't anything happen when the create product button is pressed? and when checked in the database, no new products were added

**Comment by basir** [comment]
hello there,
the issue is in zod and react hook form error.
in this line:
https://github.com/basir/next-pg-shadcn-ecommerce/blob/main/components/shared/admin/product-form.tsx#L85
```
console.log(form.formState.errors)
```
and the check chrome console to see what error do you get.
share it here to take a look.

**Comment by basir** [comment]
the issue was in banner. it should be set to null to fix this issue.
I fixed it. clone the repo and test again. it should work now.
