### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by wpkindle** [basir/next-pg-shadcn-ecommerce#5]
Failed to compile.
./components/ui/use-toast.ts
129:25  Error: 'state' is defined but never used.  no-unused-vars
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
Error: Command "npm run build" exited with 1

**Comment by basir** [comment]
it is an issue in shadcn. you can simply ignore this error by adding this line:
`// eslint-disable-next-line no-unused-vars`
here:
https://github.com/basir/next-pg-shadcn-ecommerce/blob/2ce01b587e6ecda6e115b6db8e735413f153354e/components/ui/use-toast.ts#L129

**Comment by wpkindle** [comment]
fixed, thank you
