### ISSUE TITLE
404 error after deployment

### ISSUE THREAD

**Issue by wpkindle** [basir/next-pg-shadcn-ecommerce#6]
After deployment, I'm getting 404 error on these pages

/api/auth/signin
/product/[slug]

**Comment by basir** [comment]
I can't reproduce this error in this repo. share your repo to take a look.

**Comment by wpkindle** [comment]
https://github.com/wpkindle/wp-kindle

**Comment by basir** [comment]
I cloned your repo and it works when I click on Sign In button on header menu. 
send your .env.local over email to replicate your env. email:basir.jafarzadeh@gmail.com

**Comment by wpkindle** [comment]
it is working fine on localhost, the issue raise only on vercel

**Comment by basir** [comment]
I see. you need to set this on vercel:
AUTH_SECRET=v7a59n6HN3COWeporDl4lxfKkL7UPkvVHOu0FDUetjA=
find project on vercel -> setting -> env variables -> add above item.

**Comment by wpkindle** [comment]
done, thank you so much again
