### ISSUE TITLE
Issue with Stripe Payment

### ISSUE THREAD

**Issue by LenNaidoo** [basir/next-pg-shadcn-ecommerce#7]
When I click on place order:
1. The Order Summary does not show Stripe's 'Payment Element'
2. The Order is immediately submitted to Stripe.
3. The payment is received by Stripe. It's status is incomplete - message: The customer has not entered their payment method.
4. Terminal  -  POST /place-order 303

**Comment by basir** [comment]
I can't reproduce this error in this repo. share your repo to take a look.
also in which lesson do you get this error?

**Comment by LenNaidoo** [comment]
I shared the repo with you. I got the error in lesson 32, Pay order by Stripe. Thanks

**Comment by basir** [comment]
I got 404 error when I want to accept invitation in your GitHub repo.
Remove me from collaborators and add again.

**Comment by LenNaidoo** [comment]
I re-added you as a collaborator

**Comment by basir** [comment]
I cloned and ran your code in my side and it works perfectly.
the issue is stripe config. make sure you set env variables correctly in .env.local and vercel dashboard like this:
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_????
STRIPE_SECRET_KEY=sk_test_???
STRIPE_WEBHOOK_SECRET=whsec_???

**Comment by LenNaidoo** [comment]
That was it, my STRIPE_PUBLISHABLE-KEY was incorrect. I was using pk_live_???. Thank you.

**Comment by basir** [comment]
you're welcome. glad you fixed it.
