### ISSUE TITLE
Uploadthing issue

### ISSUE THREAD

**Issue by wpkindle** [basir/next-pg-shadcn-ecommerce#8]
I'm getting 500 server error while uploading the image
![Screenshot_229](https://github.com/basir/next-pg-shadcn-ecommerce/assets/165402175/f799d85e-2f85-4a92-9e1e-e89c3ae492e8)

**Comment by basir** [comment]
I cloned and ran your code on my side and it uploads file perfectly without any error.
the issue is in uploadthing api key. make sure you set them correctly in local and vercel dashboard.
